configured_endpoints: 79
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/mirascope%2Flilypad-sdk-406a1f78a23734d0a406ab86fabe636f63ebab0ecd32aababb21a822862e0ad8.yml
openapi_spec_hash: 65e6d4b0bd3bdf4e01378ac72b74345e
config_hash: 18bfb114cbeabd381ab07bfce05ebf4c
