configured_endpoints: 85
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/mirascope%2Flilypad-sdk-5dc201ac3ca037bd1ea0cbad882784ab5312cbbbaec413b7c8caaaffe9b0eb15.yml
openapi_spec_hash: ddff49400c38d6e987fadfae7187bef2
config_hash: 63e7246cf3b4c9133ba22fcfe48a0976
